# Generated by Django 4.0.3 on 2022-04-01 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='begin',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
