# Generated by Django 4.0.3 on 2022-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_task_begin_task_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
