# Generated by Django 4.0.3 on 2022-04-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_task_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('reading', 'reading'), ('stading', 'stading'), ('sport', 'sport'), ('gaming', 'gaming')], default=('reading', 'reading'), max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('pending', 'pending'), ('starting', 'starting'), ('finiched', 'finiched')], default=('in progress', 'in progress'), max_length=50),
        ),
    ]
