# Generated by Django 4.0.3 on 2022-04-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_task_category_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('pending', 'pending'), ('starting', 'starting'), ('Done', 'Done')], default=('in progress', 'in progress'), max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
