# Generated by Django 4.0.3 on 2022-04-01 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_alter_task_status_alter_task_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
