# Generated by Django 4.0.3 on 2022-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0007_alter_task_begin_alter_task_category_alter_task_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
